### ISSUE TITLE
[DEPLOY] 1주차 배포

### ISSUE THREAD

**Issue by sbyeol3** [boostcamp-2020/IssueTracker-10#31]
## 설명
> 이슈에 대한 설명을 작성합니다. 담당자도 함께 작성하면 좋습니다.

배포 링크 : http://49.50.163.58:3000/

## 체크사항
> 이슈를 close하기 위해 필요한 조건들을 체크박스로 나열합니다.

- [ ] GET /auth/github/login
- [ ] GET /api/all
- [ ] GET /api/issue/{issueId}
- [ ] POST /api/issue 

## 참고자료
> 이슈를 해결하기 위해 필요한 참고자료가 있다면 추가합니다.

[API 명세서](https://github.com/boostcamp-2020/IssueTracker-10/wiki/API-%EB%AA%85%EC%84%B8%EC%84%9C---0.-Common)

## 관련 논의
> 이슈에 대한 논의가 있었다면 논의 내용을 간략하게 추가합니다.

**Comment by sbyeol3** [comment]
```
1|www      |     at Function.process_params (/home/byeol/IssueTracker-10/server/node_modules/express/lib/router/index.js:335:12)
1|www      |     at next (/home/byeol/IssueTracker-10/server/node_modules/express/lib/router/index.js:275:10)
1|www      |     at /home/byeol/IssueTracker-10/server/node_modules/express/lib/router/index.js:635:15
1|www      |     at next (/home/byeol/IssueTracker-10/server/node_modules/express/lib/router/index.js:260:14)
1|www      |     at Function.handle (/home/byeol/IssueTracker-10/server/node_modules/express/lib/router/index.js:174:3)
1|www      |     at router (/home/byeol/IssueTracker-10/server/node_modules/express/lib/router/index.js:47:12)
1|www      | Error: This username is already exist!
1|www      |     at Object.findOrCreateUserById (/home/byeol/IssueTracker-10/server/models/user.js:33:11)
1|www      |     at process._tickCallback (internal/process/next_tick.js:68:7)
1|www      | Error: This username is already exist!
1|www      |     at Object.findOrCreateUserById (/home/byeol/IssueTracker-10/server/models/user.js:33:11)
1|www      |     at process._tickCallback (internal/process/next_tick.js:68:7)
1|www      | Error: This username is already exist!
1|www      |     at Object.findOrCreateUserById (/home/byeol/IssueTracker-10/server/models/user.js:33:11)
1|www      |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

error : mysql 사용자 권한 추가를 안해서 테이블이 생성되지 않아 문제 발생했음. 권한 생성 후 reload
